<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Grace Ayuma's  curiculum vitae</title>
    <style>
        /* Add your CSS styles here */
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            margin: 0;
            padding: 0;
        }
        header {
            background-color: #333;
            color: #fff;
            padding: 20px 0;
            text-align: center;
            margin-bottom: 20px;
        }
        h1 {
            margin: 0;
        }
        p {
            margin: 5px 0;
        }
        section {
            margin-bottom: 30px;
            padding: 0 20px;
        }
        h2 {
            color: #333;
        }
        ul {
            padding-left: 20px;
        }
        a {
            color: #007bff;
            text-decoration: none;
        }
        a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>

    <header>
        <h1>Grace Ayuma</h1>
        <p>Full Stock Software Developer | 3 months of experience</p>
        <p>Email: gracelifelegacy@gmail.com | Phone:</p>
    </header>

    <section id="objective">
        <h2>Objective</h2>
        <p>I am a dedicated and motivated Full Stock software developer with 3 months of experience. I have acquired a variety of skills in the field of computer programming and development.</p>
    </section>
      <section>
        <h2>Skills Acquired</h2>
        <li>Computer programing</li>
        <li>Web development</li>
        <li>Database design</li>
        <li>Coding experience</li>
    </section>
    <section>
        <h2>Experiences</h2>
        I have 3+ years of experience in the field of tech.
    </section>

    <section id="education">
        <h2>Education</h2>
        <ul>
            <li>
                <h3>Mundoli ACK Girls Secondary School</h3>
                <p>Attained Kenya Certificate of Secondary Education (KCSE)</p>
                <p>Years Attended: 4 years</p>
            </li>
            <li>
                <h3>Ebuyalu Primary School</h3>
                <p>Attained Kenya Certificate of Primary Education (KCPE)</p>
                <p>Years Attended: 8 years</p>
            </li>
        </ul>
    </section>
  

    <section id="linkedin">
        <h2>LinkedIn</h2>
        <p>For more information, you can visit my <a href="https://www.linkedin.com/in/grace-ayuma-ochango-3659852b8" target="_blank">LinkedIn</a> account.</p>
    </section>

</body>
</html>
